# Generated by Django 3.2 on 2021-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(max_length=50)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='img')),
                ('discount_percentage', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('before_discount_price', models.IntegerField()),
                ('is_trending', models.BooleanField(default=False)),
                ('is_promotions', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.categories')),
                ('subCategories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategories', to='main.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('display_image', models.ImageField(upload_to='img')),
                ('product_description', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('model_name_description', models.TextField()),
                ('field_1', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='img')),
                ('description_1', models.TextField()),
                ('field_2', models.CharField(max_length=100)),
                ('image2', models.ImageField(upload_to='img')),
                ('description_2', models.TextField()),
                ('field_3', models.CharField(max_length=100)),
                ('image3', models.ImageField(upload_to='img')),
                ('description_3', models.TextField()),
                ('field_4', models.CharField(max_length=100)),
                ('image4', models.ImageField(upload_to='img')),
                ('description_4', models.TextField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_image', to='main.products')),
            ],
        ),
    ]
